### ISSUE TITLE
Enhance README for Better Clarity

### ISSUE THREAD

**Issue by Sunghyun09** [Sunghyun09/ascii_art#1]
I noticed the README could be more informative. Adding a 'Getting Started' section with setup instructions would be beneficial for newcomers to the project.

**Comment by jinyoung-plus** [comment]
Hello. Can I edit the README a little bit?

**Comment by Sunghyun09** [comment]
Yes, you can. Go ahead.

**Comment by Sunghyun09** [comment]
good job
